version: "3.7"

services:
  redis-node-0:
    image: redis:latest
    container_name: redis-cluster-entry
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
    command:
      [
        "redis-server",
        "--port",
        "7000",
        "--cluster-enabled",
        "yes",
        "--cluster-config-file",
        "/data/nodes.conf",
        "--cluster-node-timeout",
        "5000",
        "--appendonly",
        "yes",
      ]
    volumes:
      - ./data/redis-node-0:/data
  redis-node-1:
    image: redis:latest
    command:
      [
        "redis-server",
        "--port",
        "7001",
        "--cluster-enabled",
        "yes",
        "--cluster-config-file",
        "/data/nodes.conf",
        "--cluster-node-timeout",
        "5000",
        "--appendonly",
        "yes",
      ]
    network_mode: "service:redis-node-0"
    volumes:
      - ./data/redis-node-1:/data
  redis-node-2:
    image: redis:latest
    command:
      [
        "redis-server",
        "--port",
        "7002",
        "--cluster-enabled",
        "yes",
        "--cluster-config-file",
        "/data/nodes.conf",
        "--cluster-node-timeout",
        "5000",
        "--appendonly",
        "yes",
      ]
    network_mode: "service:redis-node-0"
    volumes:
      - ./data/redis-node-2:/data
  redis-node-3:
    image: redis:latest
    command:
      [
        "redis-server",
        "--port",
        "7003",
        "--cluster-enabled",
        "yes",
        "--cluster-config-file",
        "/data/nodes.conf",
        "--cluster-node-timeout",
        "5000",
        "--appendonly",
        "yes",
      ]
    network_mode: "service:redis-node-0"
    volumes:
      - ./data/redis-node-3:/data
  redis-node-4:
    image: redis:latest
    command:
      [
        "redis-server",
        "--port",
        "7004",
        "--cluster-enabled",
        "yes",
        "--cluster-config-file",
        "/data/nodes.conf",
        "--cluster-node-timeout",
        "5000",
        "--appendonly",
        "yes",
      ]
    network_mode: "service:redis-node-0"
    volumes:
      - ./data/redis-node-4:/data
  redis-node-5:
    image: redis:latest
    command:
      [
        "redis-server",
        "--port",
        "7005",
        "--cluster-enabled",
        "yes",
        "--cluster-config-file",
        "/data/nodes.conf",
        "--cluster-node-timeout",
        "5000",
        "--appendonly",
        "yes",
      ]
    network_mode: "service:redis-node-0"
    volumes:
      - ./data/redis-node-5:/data

  cluster-init:
    image: redis:latest
    command:
      [
        "sh",
        "-c",
        "sleep 1 && redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 --cluster-replicas 1 --cluster-yes",
      ]
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    network_mode: "service:redis-node-0"
